name: Update README with Stats

on:
  schedule:
    - cron: "0 */6 * * *"   # Runs every 6 hours
  workflow_dispatch:         # Allow manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Run GitHub Stats with your PAT
      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        env:
          PAT_1: ${{ secrets.PAT_1 }}
